import type { ToolCategoryDefinition, ToolDefinition } from '@/types';

export const TOOL_CATEGORIES: ToolCategoryDefinition[] = [
  {
    id: 'image-studio',
    name: 'Image Studio',
    description: 'Background removal, aspect ratio padding, resize, icons, and more',
    path: '/image-studio',
    icon: 'Image',
    prefetches: [
      'https://unpkg.com/@ffmpeg/core-mt@0.12.10/dist/umd/ffmpeg-core.wasm',
      'https://unpkg.com/@ffmpeg/core-mt@0.12.10/dist/umd/ffmpeg-core.worker.js',
    ],
  },
  {
    id: 'files-media',
    name: 'Files & Media',
    description: 'PDF tools, format conversion, merge and split audio/video',
    path: '/files-media',
    icon: 'FileVideo',
    prefetches: [
      'https://unpkg.com/pdfjs-dist@5.4.624/build/pdf.worker.min.mjs',
      'https://unpkg.com/@ffmpeg/core-mt@0.12.10/dist/umd/ffmpeg-core.wasm',
      'https://unpkg.com/@ffmpeg/core-mt@0.12.10/dist/umd/ffmpeg-core.worker.js',
    ],
  },
  {
    id: 'crypto',
    name: 'Crypto Suite',
    description: 'Hash, cipher, and JWT tools',
    path: '/crypto',
    icon: 'Lock',
  },
  {
    id: 'dev-utils',
    name: 'Dev Utils',
    description: 'Formatters, converters, encoders, diff checker, timestamps',
    path: '/dev-utils',
    icon: 'Code',
  },
  {
    id: 'generators',
    name: 'Generators',
    description: 'QR codes, color tools, gradients, and more',
    path: '/generators',
    icon: 'Wand2',
  },
];

export const TOOLS: ToolDefinition[] = [
  // Image Studio (alphabetical)
  {
    id: 'color-palette',
    name: 'Color Palette from Image',
    description: 'Extract dominant colors from any image',
    path: '/image-studio/palette',
    category: 'image-studio',
    icon: 'Pipette',
    keywords: ['color', 'palette', 'extract', 'dominant', 'image', 'swatch', 'hex', 'rgb', 'hsl'],
  },
  {
    id: 'batch-image',
    name: 'Batch Image Processing',
    description: 'Process multiple images at once — resize, convert, or compress',
    path: '/image-studio/batch',
    category: 'image-studio',
    icon: 'Images',
    keywords: ['batch', 'bulk', 'resize', 'convert', 'compress', 'multiple', 'zip'],
    hideSnippets: true,
  },
  {
    id: 'aspect-ratio-pad',
    name: 'Aspect Ratio Pad',
    description: 'Calculate ratios and pad images to any aspect ratio',
    path: '/image-studio/aspect-ratio-pad',
    category: 'image-studio',
    icon: 'RatioIcon',
    keywords: ['pad', 'ratio', 'resize', 'crop', 'square', 'calculate', 'width', 'height'],
  },
  {
    id: 'background-remover',
    name: 'Background Remover',
    description: 'Remove image backgrounds using AI',
    path: '/image-studio/background-remover',
    category: 'image-studio',
    icon: 'Eraser',
    keywords: ['bg', 'remove', 'transparent', 'cutout'],
  },
  {
    id: 'icon-generator',
    name: 'Icon Generator',
    description: 'Generate favicon, Android, Apple, and MS icon sets',
    path: '/image-studio/icon-generator',
    category: 'image-studio',
    icon: 'Layers',
    keywords: ['favicon', 'android', 'apple', 'pwa', 'icon'],
  },
  {
    id: 'image-editor',
    name: 'Image Editor',
    description: 'Resize, compress, adjust quality, and convert formats',
    path: '/image-studio/editor',
    category: 'image-studio',
    icon: 'SlidersHorizontal',
    keywords: ['resize', 'compress', 'convert', 'quality', 'format', 'optimize', 'jpeg', 'webp', 'avif'],
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    description: 'View and strip EXIF metadata from images',
    path: '/image-studio/metadata',
    category: 'image-studio',
    icon: 'FileSearch',
    keywords: ['exif', 'metadata', 'image', 'camera', 'gps', 'strip', 'viewer'],
  },
  {
    id: 'ocr',
    name: 'OCR / Text Extraction',
    description: 'Extract text from images using Tesseract.js OCR',
    path: '/image-studio/ocr',
    category: 'image-studio',
    icon: 'ScanText',
    keywords: ['ocr', 'text', 'extract', 'image', 'tesseract', 'recognition', 'scan'],
  },
  {
    id: 'pdf-from-images',
    name: 'PDF from Images',
    description: 'Create a PDF from images with drag-and-drop reorder',
    path: '/image-studio/pdf-from-images',
    category: 'image-studio',
    icon: 'FileImage',
    keywords: ['pdf', 'images', 'combine', 'photo'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Optimize SVG files with SVGO for smaller file sizes',
    path: '/image-studio/svg-optimizer',
    category: 'image-studio',
    icon: 'Shapes',
    keywords: ['svg', 'optimize', 'svgo', 'vector', 'clean', 'minify'],
  },

  // Files & Media — PDF (alphabetical)
  {
    id: 'pdf-merge',
    name: 'Merge PDFs',
    description: 'Combine multiple PDFs with page reorder',
    path: '/files-media/merge-pdf',
    category: 'files-media',
    icon: 'Combine',
    keywords: ['merge', 'combine', 'join', 'pdf'],
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    description: 'Split PDFs, extract pages, and convert to images',
    path: '/files-media/split-pdf',
    category: 'files-media',
    icon: 'FileText',
    keywords: ['split', 'extract', 'pages', 'pdf', 'image', 'convert', 'png', 'jpg'],
  },

  // Files & Media — Audio / Video (alphabetical)
  {
    id: 'media-convert',
    name: 'Format Converter',
    description: 'Convert video and audio between formats',
    path: '/files-media/convert',
    category: 'files-media',
    icon: 'RefreshCw',
    keywords: ['convert', 'video', 'audio', 'mp4', 'mp3', 'webm', 'wav'],
  },
  {
    id: 'media-merge',
    name: 'Media Merge',
    description: 'Concatenate multiple audio or video files',
    path: '/files-media/merge-media',
    category: 'files-media',
    icon: 'Combine',
    keywords: ['merge', 'concat', 'join', 'video', 'audio'],
  },
  {
    id: 'media-split',
    name: 'Media Split',
    description: 'Split audio or video at specific points',
    path: '/files-media/split-media',
    category: 'files-media',
    icon: 'Scissors',
    keywords: ['split', 'cut', 'trim', 'video', 'audio'],
  },

  // Crypto Suite (alphabetical)
  {
    id: 'cipher',
    name: 'Cipher Encode/Decode',
    description: 'AES, TripleDES, Rabbit, RC4 encryption',
    path: '/crypto/cipher',
    category: 'crypto',
    icon: 'ShieldCheck',
    keywords: ['encrypt', 'decrypt', 'aes', 'cipher'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA, and HMAC hashes',
    path: '/crypto/hash',
    category: 'crypto',
    icon: 'Hash',
    keywords: ['hash', 'md5', 'sha', 'hmac', 'checksum'],
  },
  {
    id: 'jwt',
    name: 'JWT Encode/Decode',
    description: 'Decode, verify, and sign JSON Web Tokens',
    path: '/crypto/jwt',
    category: 'crypto',
    icon: 'KeyRound',
    keywords: ['jwt', 'token', 'json', 'verify', 'sign'],
  },
  {
    id: 'ssh-keygen',
    name: 'SSH Key Generator',
    description: 'Generate SSH key pairs (Ed25519, RSA) using WebCrypto',
    path: '/crypto/ssh-keygen',
    category: 'crypto',
    icon: 'KeySquare',
    keywords: ['ssh', 'key', 'generate', 'ed25519', 'rsa', 'public', 'private', 'keypair'],
  },

  // Dev Utils (alphabetical)
  {
    id: 'data-viz',
    name: 'Data Visualization',
    description: 'Paste JSON or CSV, generate interactive charts instantly',
    path: '/dev-utils/data-viz',
    category: 'dev-utils',
    icon: 'BarChart3',
    keywords: ['chart', 'graph', 'bar', 'line', 'pie', 'scatter', 'area', 'json', 'csv', 'visualize', 'data'],
  },
  {
    id: 'api-tester',
    name: 'API Request Tester',
    description: 'Test REST, GraphQL, and WebSocket endpoints with cURL import and code generation',
    path: '/dev-utils/api-tester',
    category: 'dev-utils',
    icon: 'Globe',
    keywords: ['api', 'http', 'request', 'rest', 'postman', 'fetch', 'get', 'post', 'put', 'delete', 'curl', 'axios', 'python', 'code', 'graphql', 'websocket', 'ws', 'subscription', 'query', 'mutation'],
  },
  {
    id: 'code-formatter',
    name: 'Code Formatter',
    description: 'Format HTML, CSS, JS, TS, JSON, Markdown, and SQL',
    path: '/dev-utils/code-formatter',
    category: 'dev-utils',
    icon: 'Code',
    keywords: ['format', 'beautify', 'prettier', 'html', 'css', 'javascript', 'typescript', 'json', 'sql'],
  },
  {
    id: 'code-playground',
    name: 'Code Playground',
    description: 'Run JavaScript, TypeScript, and Python code in the browser with Monaco editor',
    path: '/dev-utils/code-playground',
    category: 'dev-utils',
    icon: 'Play',
    keywords: ['code', 'playground', 'run', 'execute', 'javascript', 'typescript', 'python', 'repl', 'sandbox'],
    hideSnippets: true,
  },
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    description: 'Build cron expressions visually with next run times',
    path: '/dev-utils/cron-builder',
    category: 'dev-utils',
    icon: 'Timer',
    keywords: ['cron', 'schedule', 'expression', 'builder', 'job'],
  },
  {
    id: 'diagram',
    name: 'Diagram Generator',
    description: 'Create flowcharts, sequence, class, ER, Gantt, and mind map diagrams from Mermaid syntax',
    path: '/dev-utils/diagram',
    category: 'dev-utils',
    icon: 'Workflow',
    keywords: ['diagram', 'mermaid', 'flowchart', 'sequence', 'class', 'er', 'gantt', 'mindmap', 'chart'],
  },
  {
    id: 'db-playground',
    name: 'Database Playground',
    description: 'Run SQL queries against an in-browser SQLite database with Monaco editor',
    path: '/dev-utils/db-playground',
    category: 'dev-utils',
    icon: 'Database',
    keywords: ['sql', 'database', 'sqlite', 'query', 'table', 'select', 'insert', 'update', 'delete', 'schema'],
    hideSnippets: true,
  },
  {
    id: 'dev-misc',
    name: 'Dev Misc',
    description: 'Byte counter, chmod calculator, OG preview, URL parser, and fake data generator',
    path: '/dev-utils/misc',
    category: 'dev-utils',
    icon: 'MoreHorizontal',
    keywords: ['byte', 'count', 'chmod', 'permissions', 'og', 'opengraph', 'preview', 'misc', 'url', 'parse', 'fake', 'data', 'mock', 'generate'],
    hideSnippets: true,
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text line-by-line, word, char, sentence, or JSON semantic diff',
    path: '/dev-utils/diff-checker',
    category: 'dev-utils',
    icon: 'GitCompare',
    keywords: ['diff', 'compare', 'merge', 'text', 'json', 'semantic'],
  },
  {
    id: 'json-yaml-xml',
    name: 'Data Format Tools',
    description: 'Convert, validate, format JSON/YAML/XML/CSV, validate against JSON Schema, generate TypeScript types',
    path: '/dev-utils/json-yaml-xml',
    category: 'dev-utils',
    icon: 'Braces',
    keywords: ['json', 'yaml', 'xml', 'csv', 'format', 'validate', 'convert', 'tree', 'jsonpath', 'explore', 'table', 'spreadsheet', 'schema', 'ajv', 'typescript', 'ts', 'interface', 'type', 'generate'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Editor',
    description: 'Write Markdown with live preview, export to HTML or PDF',
    path: '/dev-utils/markdown',
    category: 'dev-utils',
    icon: 'TextQuote',
    keywords: ['markdown', 'md', 'preview', 'render', 'html', 'pdf', 'export', 'print'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live highlighting and match groups',
    path: '/dev-utils/regex',
    category: 'dev-utils',
    icon: 'Regex',
    keywords: ['regex', 'regexp', 'regular', 'expression', 'pattern', 'match', 'test'],
  },
  {
    id: 'text-case',
    name: 'Text Case Converter',
    description: 'Convert text between camelCase, snake_case, Title Case, and more',
    path: '/dev-utils/text-case',
    category: 'dev-utils',
    icon: 'ALargeSmall',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'upper', 'lower', 'title'],
  },
  {
    id: 'text-encoders',
    name: 'Text Encoders',
    description: 'Base64, URL encode/decode, and HTML entity encoder/decoder',
    path: '/dev-utils/encoders',
    category: 'dev-utils',
    icon: 'FileCode',
    keywords: ['base64', 'url', 'encode', 'decode', 'html', 'entity', 'uri', 'escape', 'percent'],
  },
  {
    id: 'timestamp',
    name: 'Time & Epoch',
    description: 'UTC, local, epoch, cron, countdown, and stopwatch',
    path: '/dev-utils/timestamp',
    category: 'dev-utils',
    icon: 'Clock',
    keywords: ['timestamp', 'epoch', 'utc', 'cron', 'date', 'time', 'countdown', 'stopwatch', 'timer', 'lap'],
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    description: 'Freeform drawing and diagramming',
    path: '/dev-utils/whiteboard',
    category: 'dev-utils',
    icon: 'PenTool',
    keywords: ['draw', 'diagram', 'sketch', 'excalidraw', 'whiteboard'],
  },

  // Generators (alphabetical)
  {
    id: 'ascii-art',
    name: 'ASCII Art Generator',
    description: 'Convert text to ASCII art with multiple font styles',
    path: '/generators/ascii-art',
    category: 'generators',
    icon: 'Type',
    keywords: ['ascii', 'art', 'text', 'font', 'figlet', 'banner', 'generator'],
  },
  {
    id: 'color-picker',
    name: 'Color & Gradient Tools',
    description: 'Pick colors, create gradients, convert HEX/RGB/HSL, and check contrast',
    path: '/generators/color-picker',
    category: 'generators',
    icon: 'Palette',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'gradient', 'css', 'contrast', 'wcag', 'shades', 'picker'],
  },
  {
    id: 'image-placeholder',
    name: 'Image Placeholder',
    description: 'Generate placeholder images with custom size, colors, and text',
    path: '/generators/placeholder',
    category: 'generators',
    icon: 'ImagePlus',
    keywords: ['placeholder', 'image', 'dummy', 'mock', 'size', 'color', 'text', 'generate'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong passwords with custom character sets',
    path: '/generators/password',
    category: 'generators',
    icon: 'ShieldCheck',
    keywords: ['password', 'generate', 'strong', 'random', 'secure'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes with custom size, colors, and error correction',
    path: '/generators/qr-code',
    category: 'generators',
    icon: 'QrCode',
    keywords: ['qr', 'code', 'barcode', 'scan', 'url'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID / ULID Generator',
    description: 'Generate UUID v4 and ULID with batch mode',
    path: '/generators/uuid',
    category: 'generators',
    icon: 'Fingerprint',
    keywords: ['uuid', 'ulid', 'guid', 'unique', 'id', 'generate'],
  },
];
